"""构建默认废弃物类别知识种子。"""

from __future__ import annotations

from typing import List

from wastekg.core.models import CategorySpec
from wastekg.graph.store import KnowledgeGraph


EPA_CDM_SOURCE = "https://www.epa.gov/smm/sustainable-management-construction-and-demolition-materials"


DEFAULT_CATEGORY_SPECS: List[CategorySpec] = [
    CategorySpec(
        name="concrete",
        category="building_waste",
        material="mineral",
        risk_level="medium",
        fragility="low",
        graspability="low",
        pollution_level="low",
        recognition_difficulty="medium",
        handling_mode="robot_with_supervision",
        grasp_difficulty="high",
        needs_llm_review=False,
        auto_processable=False,
        recyclability="high",
        semantic_tags=["heavy", "mineral", "rubble"],
        visual_prototype={
            "common_colors": ["gray", "light_gray", "off_white"],
            "surface_texture": ["rough", "granular", "dusty"],
            "transparency": ["opaque"],
            "gloss": ["low"],
            "edge_shape": ["irregular", "broken"],
            "shape_cue": ["fragment", "block"],
        },
        confidence_prior=0.85,
        description="混凝土块、碎混凝土以及本项目中归并的石头/骨料类对象。",
        source_refs=[EPA_CDM_SOURCE],
        notes="重量和不规则形状会增加夹爪抓取难度；石头和 aggregate 在本项目中统一映射为 concrete。",
    ),
    CategorySpec(
        name="brick",
        category="building_waste",
        material="ceramic",
        risk_level="medium",
        fragility="low",
        graspability="medium",
        pollution_level="low",
        recognition_difficulty="low",
        handling_mode="robot_grasp",
        grasp_difficulty="medium",
        needs_llm_review=False,
        auto_processable=True,
        recyclability="medium",
        semantic_tags=["masonry", "rigid", "rubble"],
        visual_prototype={
            "common_colors": ["red", "brown", "orange", "gray"],
            "surface_texture": ["rough", "porous", "masonry_like"],
            "transparency": ["opaque"],
            "gloss": ["low"],
            "edge_shape": ["blocky", "broken", "rectangular"],
            "shape_cue": ["block", "fragment"],
        },
        confidence_prior=0.88,
        description="砖块或砖块碎片，边界和颜色特征通常较稳定。",
        source_refs=[EPA_CDM_SOURCE],
        notes="适合作为第一阶段自动夹取和规划测试对象。",
    ),
    CategorySpec(
        name="tile",
        category="building_waste",
        material="ceramic",
        risk_level="medium",
        fragility="medium",
        graspability="medium",
        pollution_level="low",
        recognition_difficulty="medium",
        handling_mode="robot_with_supervision",
        grasp_difficulty="medium",
        needs_llm_review=False,
        auto_processable=True,
        recyclability="medium",
        semantic_tags=["flat", "ceramic", "fragment"],
        visual_prototype={
            "common_colors": ["gray", "brown", "red", "off_white", "various"],
            "surface_texture": ["smooth", "ceramic_like", "dusty"],
            "transparency": ["opaque"],
            "gloss": ["low", "medium"],
            "edge_shape": ["flat", "thin", "sharp", "broken"],
            "shape_cue": ["plate_like", "fragment"],
        },
        confidence_prior=0.82,
        description="瓷砖、瓦片或类似片状硬质建筑碎片。",
        source_refs=[EPA_CDM_SOURCE],
        notes="片状物可能较薄，抓取时需要结合深度图判断夹爪接近方向。",
    ),
    CategorySpec(
        name="wood",
        category="building_waste",
        material="organic",
        risk_level="low",
        fragility="low",
        graspability="medium",
        pollution_level="low",
        recognition_difficulty="low",
        handling_mode="robot_grasp",
        grasp_difficulty="medium",
        needs_llm_review=False,
        auto_processable=True,
        recyclability="high",
        semantic_tags=["fibrous", "timber", "board"],
        visual_prototype={
            "common_colors": ["brown", "yellow_brown", "light_brown", "dark_brown"],
            "surface_texture": ["fibrous", "linear_grain", "rough"],
            "transparency": ["opaque"],
            "gloss": ["low", "medium"],
            "edge_shape": ["straight", "splintered", "broken"],
            "shape_cue": ["board", "strip", "block"],
        },
        confidence_prior=0.82,
        description="木材、木板、木方等建筑或包装废弃木质材料。",
        source_refs=[EPA_CDM_SOURCE],
        notes="timber 在本项目中映射为 wood；若实例存在油漆、钉子或尖锐断面，可在短期状态中提高风险。",
    ),
    CategorySpec(
        name="gypsum_board",
        category="building_waste",
        material="mineral_board",
        risk_level="medium",
        fragility="high",
        graspability="low",
        pollution_level="medium",
        recognition_difficulty="medium",
        handling_mode="human_review",
        grasp_difficulty="high",
        needs_llm_review=True,
        auto_processable=False,
        recyclability="medium",
        semantic_tags=["drywall", "board", "powder_prone"],
        visual_prototype={
            "common_colors": ["white", "off_white", "gray"],
            "surface_texture": ["powdery", "paper_faced", "chalky"],
            "transparency": ["opaque"],
            "gloss": ["low"],
            "edge_shape": ["flat", "layered", "broken"],
            "shape_cue": ["board", "plate_like"],
        },
        confidence_prior=0.84,
        description="石膏板、干墙板一类材料，常见于室内装修和拆除废弃物。",
        source_refs=[EPA_CDM_SOURCE],
        notes="易碎且易产生粉尘，默认不作为夹爪自动处理优先对象。",
    ),
    CategorySpec(
        name="foam",
        category="building_waste",
        material="polymer_foam",
        risk_level="low",
        fragility="low",
        graspability="medium",
        pollution_level="medium",
        recognition_difficulty="medium",
        handling_mode="robot_with_supervision",
        grasp_difficulty="medium",
        needs_llm_review=True,
        auto_processable=True,
        recyclability="low",
        semantic_tags=["lightweight", "porous", "deformable"],
        visual_prototype={
            "common_colors": ["white", "yellow", "pink", "gray", "various"],
            "surface_texture": ["porous", "cellular", "soft"],
            "transparency": ["opaque"],
            "gloss": ["low"],
            "edge_shape": ["irregular", "soft_edge", "broken"],
            "shape_cue": ["lightweight_piece", "block", "sheet"],
        },
        confidence_prior=0.70,
        description="泡沫类建筑或包装废弃物，形态轻且易变形。",
        source_refs=[],
        notes="视觉外观变化较大，低置信度时建议大模型复核。",
    ),
    CategorySpec(
        name="metal",
        category="building_waste",
        material="metal",
        risk_level="medium",
        fragility="low",
        graspability="medium",
        pollution_level="low",
        recognition_difficulty="medium",
        handling_mode="robot_with_supervision",
        grasp_difficulty="medium",
        needs_llm_review=True,
        auto_processable=True,
        recyclability="high",
        semantic_tags=["rigid", "reflective", "sharp_edge_possible"],
        visual_prototype={
            "common_colors": ["silver", "gray", "dark_gray", "rust"],
            "surface_texture": ["smooth", "reflective", "scratched"],
            "transparency": ["opaque"],
            "gloss": ["medium", "high"],
            "edge_shape": ["sharp", "regular", "bent"],
            "shape_cue": ["sheet", "rod", "piece"],
        },
        confidence_prior=0.90,
        description="金属类废弃物，包括金属块、金属板、金属碎件等。",
        source_refs=[EPA_CDM_SOURCE],
        notes="边缘锋利或反光会影响识别和抓取，低置信度时建议复核。",
    ),
    CategorySpec(
        name="soft_plastic",
        category="recyclable_waste",
        material="plastic",
        risk_level="low",
        fragility="low",
        graspability="medium",
        pollution_level="medium",
        recognition_difficulty="medium",
        handling_mode="robot_with_supervision",
        grasp_difficulty="medium",
        needs_llm_review=True,
        auto_processable=True,
        recyclability="medium",
        semantic_tags=["lightweight", "deformable", "film_or_soft_piece"],
        visual_prototype={
            "common_colors": ["various"],
            "surface_texture": ["wrinkled", "thin", "flexible"],
            "transparency": ["opaque", "translucent", "transparent"],
            "gloss": ["low", "medium", "high"],
            "edge_shape": ["folded", "irregular", "soft_edge"],
            "shape_cue": ["film", "bag", "sheet"],
        },
        confidence_prior=0.72,
        description="柔性塑料或软质塑料包装，通常轻、易变形。",
        source_refs=[EPA_CDM_SOURCE],
        notes="柔性形变会影响夹爪抓取稳定性，建议结合分割掩膜和深度判断。",
    ),
    CategorySpec(
        name="hard_plastic",
        category="recyclable_waste",
        material="plastic",
        risk_level="low",
        fragility="low",
        graspability="medium",
        pollution_level="medium",
        recognition_difficulty="medium",
        handling_mode="robot_grasp",
        grasp_difficulty="medium",
        needs_llm_review=True,
        auto_processable=True,
        recyclability="medium",
        semantic_tags=["rigid", "pipe_or_container", "hard_piece"],
        visual_prototype={
            "common_colors": ["various"],
            "surface_texture": ["smooth", "rigid", "molded"],
            "transparency": ["opaque", "translucent", "transparent"],
            "gloss": ["medium", "high"],
            "edge_shape": ["regular", "curved", "broken"],
            "shape_cue": ["container", "pipe", "fragment"],
        },
        confidence_prior=0.74,
        description="硬质塑料件；本项目中 pipe/pipes 和未细分 plastic 默认映射到该类。",
        source_refs=[EPA_CDM_SOURCE],
        notes="适合第一阶段夹爪处理，但细长管状物需要在短期状态中判断姿态。",
    ),
    CategorySpec(
        name="paperboard",
        category="recyclable_waste",
        material="paper_fiber",
        risk_level="low",
        fragility="medium",
        graspability="medium",
        pollution_level="low",
        recognition_difficulty="medium",
        handling_mode="robot_with_supervision",
        grasp_difficulty="medium",
        needs_llm_review=True,
        auto_processable=True,
        recyclability="high",
        semantic_tags=["flat", "foldable", "fiber_based"],
        visual_prototype={
            "common_colors": ["brown", "tan", "white", "gray"],
            "surface_texture": ["fibrous", "paper_like", "corrugated"],
            "transparency": ["opaque"],
            "gloss": ["low"],
            "edge_shape": ["flat", "folded", "torn"],
            "shape_cue": ["sheet", "box_piece", "board"],
        },
        confidence_prior=0.68,
        description="纸板、纸箱类材料，cardboard 在本项目中映射为 paperboard。",
        source_refs=[EPA_CDM_SOURCE],
        notes="受潮或污染时可回收性和抓取稳定性下降，应在短期实例属性中更新。",
    ),
    CategorySpec(
        name="glass",
        category="building_waste",
        material="silicate",
        risk_level="medium",
        fragility="high",
        graspability="low",
        pollution_level="low",
        recognition_difficulty="high",
        handling_mode="robot_with_supervision",
        grasp_difficulty="high",
        needs_llm_review=True,
        auto_processable=False,
        recyclability="high",
        semantic_tags=["transparent_or_translucent", "sharp_fragment", "brittle"],
        visual_prototype={
            "common_colors": ["transparent", "green", "brown", "blue", "clear"],
            "surface_texture": ["smooth", "reflective"],
            "transparency": ["transparent", "translucent"],
            "gloss": ["high"],
            "edge_shape": ["sharp", "thin", "broken"],
            "shape_cue": ["fragment", "sheet"],
        },
        confidence_prior=0.60,
        description="玻璃及其碎片，属于高易碎、低可抓握对象。",
        source_refs=[EPA_CDM_SOURCE],
        notes="当前本地数据支撑不足；可继续从 Roboflow Universe 等来源查找玻璃训练材料，进入规划前默认需要复核或人工确认。",
    ),
]


def seed_default_categories(graph: KnowledgeGraph) -> List[str]:
    # 长期知识只保存稳定且会影响识别、风险、夹取和规划的类别先验。
    registered: List[str] = []
    for spec in DEFAULT_CATEGORY_SPECS:
        graph.register_category(spec)
        registered.append(spec.name)
    return registered
