"""定义废弃物视觉类别、别名映射和 unknown 边界。"""

from __future__ import annotations


KNOWN_VISUAL_CLASSES = [
    "concrete",
    "brick",
    "tile",
    "wood",
    "gypsum_board",
    "foam",
    "metal",
    "soft_plastic",
    "hard_plastic",
    "paperboard",
    "glass",
]

UNKNOWN_CATEGORY = "unknown"

# Backward-compatible alias: the current visual model is intentionally scoped to
# 11 explicit classes. ``unknown`` is generated by system logic, not trained as a
# YOLO class.
PAPER_VISUAL_CLASSES = list(KNOWN_VISUAL_CLASSES)
WASTE12_CLASSES = list(KNOWN_VISUAL_CLASSES)

CLASS_TO_ID = {name: index for index, name in enumerate(KNOWN_VISUAL_CLASSES)}


CANONICAL_CATEGORY_ALIASES = {
    "stone": "concrete",
    "aggregate": "concrete",
    "pipes": "hard_plastic",
    "pipe": "hard_plastic",
    "plastic": "hard_plastic",
    "cardboard": "paperboard",
    "timber": "wood",
    "gypsum": "gypsum_board",
    "asbestos": UNKNOWN_CATEGORY,
    "asbestos_suspect": UNKNOWN_CATEGORY,
    "unknown": UNKNOWN_CATEGORY,
}


def canonicalize_category_name(name: str) -> str:
    normalized = name.strip().lower().replace(" ", "_").replace("-", "_")
    return CANONICAL_CATEGORY_ALIASES.get(normalized, normalized)
