from __future__ import annotations

from typing import Iterable, List

from .models import CategorySpec
from .store import KnowledgeGraph


EPA_CDM_SOURCE = "https://www.epa.gov/smm/sustainable-management-construction-and-demolition-materials"
OSHA_ASBESTOS_SOURCE = "https://www.osha.gov/asbestos"


DEFAULT_CATEGORY_SPECS: List[CategorySpec] = [
    CategorySpec(
        name="soft_plastic",
        category="recyclable_waste",
        material="plastic",
        risk_level="low",
        fragility="low",
        graspability="medium",
        pollution_level="medium",
        recyclability="medium",
        semantic_tags=["lightweight", "deformable", "film_or_soft_piece"],
        confidence_prior=0.72,
        description="柔性塑料或软质塑料包装，通常轻、易变形，常见于混合建筑垃圾或包装废弃物中。",
        source_refs=[EPA_CDM_SOURCE],
        notes="风险、易碎性和可抓握性为面向机器人分拣的工程化离散标签；物理属性为经验归纳。",
    ),
    CategorySpec(
        name="hard_plastic",
        category="recyclable_waste",
        material="plastic",
        risk_level="low",
        fragility="low",
        graspability="medium",
        pollution_level="medium",
        recyclability="medium",
        semantic_tags=["rigid", "container", "hard_piece"],
        confidence_prior=0.70,
        description="硬质塑料件，如硬壳包装、硬塑料碎片等，整体稳定性较高。",
        source_refs=[EPA_CDM_SOURCE],
        notes="常作为混合可回收物出现；实际可回收性取决于污染和材质纯度。",
    ),
    CategorySpec(
        name="concrete",
        category="building_waste",
        material="mineral",
        risk_level="medium",
        fragility="low",
        graspability="low",
        pollution_level="low",
        recyclability="high",
        semantic_tags=["heavy", "mineral", "rubble"],
        confidence_prior=0.85,
        description="混凝土块、碎混凝土或混凝土碎片，典型建筑拆除废弃物。",
        source_refs=[EPA_CDM_SOURCE],
        notes="重量大、搬运负担高；风险主要来自重量、飞溅粉尘和夹伤，而非化学毒性。",
    ),
    CategorySpec(
        name="brick",
        category="building_waste",
        material="ceramic",
        risk_level="medium",
        fragility="low",
        graspability="low",
        pollution_level="low",
        recyclability="medium",
        semantic_tags=["masonry", "heavy", "rubble"],
        confidence_prior=0.88,
        description="砖块或砖块碎片，属于典型建筑拆除物，通常重量较大。",
        source_refs=[EPA_CDM_SOURCE],
        notes="风险主要来自重量、边缘磕碰和堆叠不稳定；易碎性低于玻璃和石膏板。",
    ),
    CategorySpec(
        name="paperboard",
        category="recyclable_waste",
        material="paper_fiber",
        risk_level="low",
        fragility="medium",
        graspability="medium",
        pollution_level="low",
        recyclability="high",
        semantic_tags=["flat", "foldable", "fiber_based"],
        confidence_prior=0.68,
        description="纸板、纸箱类材料，通常轻且容易折叠，易受潮污染。",
        source_refs=[EPA_CDM_SOURCE],
        notes="若受潮或被污染，可回收性会下降；机器人抓取时要注意形变。",
    ),
    CategorySpec(
        name="asphalt",
        category="building_waste",
        material="bituminous",
        risk_level="medium",
        fragility="low",
        graspability="low",
        pollution_level="medium",
        recyclability="medium",
        semantic_tags=["dark", "dense", "road_material"],
        confidence_prior=0.75,
        description="沥青或沥青类拆除材料，常见于道路和屋面废弃物。",
        source_refs=[EPA_CDM_SOURCE],
        notes="风险主要来自重、脏、温度/粘附性和粉尘，不属于高毒类，但处理时较麻烦。",
    ),
    CategorySpec(
        name="wood",
        category="building_waste",
        material="organic",
        risk_level="low",
        fragility="medium",
        graspability="medium",
        pollution_level="low",
        recyclability="high",
        semantic_tags=["fibrous", "light_to_medium_weight", "structural"],
        confidence_prior=0.82,
        description="木材、木板、木方等建筑和包装废弃木质材料。",
        source_refs=[EPA_CDM_SOURCE],
        notes="若被油漆、胶黏剂或防腐剂污染，污染等级应上调。",
    ),
    CategorySpec(
        name="metal",
        category="building_waste",
        material="metal",
        risk_level="medium",
        fragility="low",
        graspability="medium",
        pollution_level="low",
        recyclability="high",
        semantic_tags=["rigid", "conductive", "sharp_edge_possible"],
        confidence_prior=0.90,
        description="金属类废弃物，包括金属块、金属板、金属碎件等。",
        source_refs=[EPA_CDM_SOURCE],
        notes="风险主要来自边缘锋利、重量和夹伤；若有锈蚀或油污，可在实例层再提高风险。",
    ),
    CategorySpec(
        name="gypsum",
        category="building_waste",
        material="mineral_board",
        risk_level="medium",
        fragility="high",
        graspability="low",
        pollution_level="low",
        recyclability="medium",
        semantic_tags=["drywall", "board", "powder_prone"],
        confidence_prior=0.84,
        description="石膏板、干墙板一类材料，常见于室内装修和拆除废弃物。",
        source_refs=[EPA_CDM_SOURCE],
        notes="易破碎、易产生粉尘，机器人抓取时应谨慎，适合先处理暴露明显的块体。",
    ),
    CategorySpec(
        name="glass",
        category="building_waste",
        material="silicate",
        risk_level="medium",
        fragility="high",
        graspability="low",
        pollution_level="low",
        recyclability="high",
        semantic_tags=["transparent_or_translucent", "sharp_fragment", "brittle"],
        confidence_prior=0.86,
        description="玻璃及其碎片，常见于窗玻璃、容器和装饰材料拆除场景。",
        source_refs=[EPA_CDM_SOURCE],
        notes="这是机器人分拣中典型的高易碎、低可抓握材料；风险等级取中是为了反映碎片割伤风险。",
    ),
    CategorySpec(
        name="asbestos",
        category="hazardous_waste",
        material="fibrous_silicate",
        risk_level="high",
        fragility="high",
        graspability="low",
        pollution_level="high",
        recyclability="low",
        semantic_tags=["hazardous", "fibrous", "friable_risk"],
        confidence_prior=0.92,
        description="石棉或疑似含石棉材料，属于高风险危险废弃物，应优先隔离和人工确认。",
        source_refs=[OSHA_ASBESTOS_SOURCE],
        notes="OSHA 明确指出石棉会导致严重健康危害；对机器人系统应默认高风险处理。",
    ),
    CategorySpec(
        name="waste_paint_can",
        category="hazardous_waste",
        material="metal",
        risk_level="high",
        fragility="low",
        graspability="low",
        pollution_level="medium",
        recyclability="low",
        semantic_tags=["container", "possible_residue", "chemical_risk"],
        confidence_prior=0.78,
        description="废油漆桶或疑似残留油漆/溶剂的容器，风险通常高于普通金属容器。",
        source_refs=[],
        notes="该条目主要是工程判定：一旦存在残留油漆、溶剂或未知污染物，应按高风险危险容器对待。",
    ),
]


def seed_default_categories(graph: KnowledgeGraph) -> List[str]:
    # 把长期知识一次性写入图谱，作为后续识别和规划的先验底座。
    registered: List[str] = []
    for spec in DEFAULT_CATEGORY_SPECS:
        graph.register_category(spec)
        registered.append(spec.name)
    return registered

